### ISSUE TITLE
sys.platform is wrong

### ISSUE THREAD

**Issue by isuruf** [benfogle/crossenv#28]
sys.platform in cross-python is that of the build python instead of the host python. Is it possible to fix that?

**Comment by benfogle** [comment]
Maybe? Crossenv currently only supports Linux build machines because of things like sys.platform. There are well over a hundred sys.platform checks in the standard library, and many of them need to be "wrong." For example, the subprocess module uses this value to decide what low-level functions to call; you won't get anywhere calling posix_spawn when the the build machine is Windows. The uuid module uses them to figure out how to get a MAC address for uuid.uuid1(). Then distutils is just littered with them in ways that might need to be "right." Third party packages are another can of worms entirely.

What build machine are you using, if not Linux? Does crossenv work to build a variety of packages, including something nontrivial, like numpy? Can it build something really involved, like scipy? (Note: scipy is actually very tricky, so don't think I'm telling you must get it to build.) Does it require this patch to work?

I'm not opposed to setting sys.platform if it's required for an Mac build machine, or something, but it should *definitely* come with a warning at environment creation time that this is not a supported use case.

**Comment by isuruf** [comment]
I'm on a Linux machine, trying to cross compile for macOS. I didn't realize that setting this would trip subprocess module and other standard modules.

Without this patch numpy works fine without BLAS libraries. Issue is that there are some calls to `sys.platform` in numpy to check that a BLAS library is present and numpy fails to find it.

**Comment by benfogle** [comment]
Well, it *might* trip up standard modules, that's the problem. Often, as you've seen, it doesn't, or at least not the ones you're using. I hadn't really considered non-embedded use cases for crossenv, but what you're trying to do is interesting.

To get BLAS libraries working with stock crossenv, try adding [site.cfg](https://github.com/numpy/numpy/blob/master/site.cfg.example) to force the correct library locations.

**Comment by jvolkman** [comment]
@benfogle sorry to dig up this old issue, but I wanted to share a thought I had. I'm also looking to compile cross-os and it seems like we're so close (at least for some combinations).

Python 3.7 added support for module-level `__getattr__`. With that, we can change the value of `sys.platform` contextually. E.g., at the bottom of `site.py`:

```python
orig_sys_platform = sys.platform
cross_sys_platform = "darwin"

import traceback
def sys_getattr(name):
    if name != 'platform':
        raise AttributeError(name)
    frames = traceback.extract_stack(limit=2)
    assert len(frames) == 2
    frame = frames[0]
    #print(frame)

    # frozen modules - part of the interpreter itself?
    if frame.filename.startswith("<frozen"):
        return orig_sys_platform
    # Report cross platform to distutils
    elif "distutils/" in frame.filename:
        return cross_sys_platform
    # Report cross platform to anything local
    # (e.g., setup.py in the module we're building)
    elif not frame.filename.startswith("/"):
        return cross_sys_platform
    
    # Report original platform to everything
    # else
    else:
        return orig_sys_platform

del sys.platform
sys.__getattr__ = sys_getattr
```

I didn't spend much time on the original vs. cross if/else block, so it may make more sense to do something like stdlib gets original, everything else (including distutils) gets cross. With this change plus a couple other small things (like fixing `os.uname` to return a proper struct for macos), numpy builds.

Given you've been looking at this space for years: does this seem like a reasonable path forward? Or are there too many gotchas?

**Comment by benfogle** [comment]
The first issue I see is that RHEL 8 (EOL 2024) and Ubuntu 18.04 (EOL 2023) come with 3.6 and are supported until 2024, so 3.6 is a reasonable target to support until then, even if it's officially EOL itself.

My other concern is that we might end up needing function-level granularity, if parts of stdlib want difference perspectives. It's not too bad to inspect the stack trace to get the caller. I just don't know what sort of work would be involved to cover all major cases, or how much we would need to concern ourselves with third party modules in practice.
