### ISSUE TITLE
Error with clang based android build of python (yan12125/python3-android)

### ISSUE THREAD

**Issue by textshell** [benfogle/crossenv#3]
I'm trying to use crossenv with a python build for android via https://github.com/yan12125/python3-android . This builds python with clang from google's android ndk.

I get the following error:

```
$ venv-native-only/bin/python -m crossenv python3-android/build/target/python/usr/bin/python3.8m venv-cross
clang: error: unknown argument: '-print-sysroot'
clang: error: no input files
ERROR: Command '['/home/build/dev/python3-android/venv-cross/build/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.
```

**Comment by benfogle** [comment]
I'll create an issue to make a better error message. The problem is with clang, crossenv can't automatically determine where the compiler sysroot should be.

You can manually specify the sysroot with the --sysroot option to crossenv. For the Android NDK , the sysroot should be $ANDROID_NDK/sysroot.

Let me know if that helps.

**Comment by benfogle** [comment]
On further investigation, I'm not sure exactly what the problem is. Can you re-run that command with "-vv" to enable the debug traceback?
