### ISSUE TITLE
qcc fails all tests in find_compiler_info()

### ISSUE THREAD

**Issue by willmmiles** [benfogle/crossenv#78]
I'm using crossenv to cross-compile Python modules for QNX, using QNX's qcc cross-compiler driver.  Unfortunately qcc doesn't support any of the flags in find_compiler_info() -- no --version, no -print-sysroot, and no -dumpmachine.   As a workaround I'm just commenting out the call to `find_compiler_info()` in the `CrossEnvBuilder` constructor, after which everything works great, but I'd like to look for a more permanent solution than modifying the source code after installation.

What would be the best way to manage different compilers?   An option to disable the sanity checks?   Expanding the sanity test to test-compile a short program (similar to how autotools does) rather than rely on possibly-unsupported flags?   I don't know if there's a truly universal way to check the sysroot or target type.

**Comment by benfogle** [comment]
I think the only flag that's currently required is `--version`, which is really just a test to see if we can successfully run the compiler.

I think it would be fine to use `shutil.which` to verify the compiler's existence, and make the `--version` test a warning. I don't want to remove it completely, because it can be useful to catch things early like missing libraries.

**Comment by benfogle** [comment]
Does #80 fix the issue for you? I don't have a qcc to test this myself.

**Comment by willmmiles** [comment]
Thanks for looking in to this! I'll run it through my QNX build system first thing tomorrow.

**Comment by willmmiles** [comment]
I can confirm it is working for me with qcc.  Thank you very much!
